### ISSUE TITLE
? can someone make a short tutorial for setting this up

### ISSUE THREAD

**Issue by GGrandma** [shanetechwiz/node-steamcardbot#10]
Example, what do certain thins under message mean in the config, trade link is the bots trade url? Context id?

Also getting this error when starting: 

> TypeError: Cannot read property 'low' of undefined

**Comment by Unparanormal** [comment]
Agreed, there are very special people here with very little coding language known.

**Comment by SloRunner** [comment]
Gonna do my best when i have time ;)
