### ISSUE TITLE
*Question* Running on a raspberry pi?

### ISSUE THREAD

**Issue by GGrandma** [shanetechwiz/node-steamcardbot#12]
Just wondering if anyone thinks this will run smoothly on a raspberry pi. It's the newest model, 3B. 4 core 1 GHz cpu, 1 GB of RAM. I know this will start up and work but when it starts to make larger trades, that's what I don't know about.

**Comment by SloRunner** [comment]
well i have same model too, gonna check it out, just need to get some sets and test the memory out

**Comment by GGrandma** [comment]
Alright thx, I would test it out myself but im waiting for my trade ban to end.

**Comment by SloRunner** [comment]
well gonna need to buy some sets for this, so maybe you should test it when your trade ban passes by?

**Comment by GGrandma** [comment]
Not to sure about this anymore, can’t get it to run as the highest version of node I can find is 4.x, when I have the time I’ll look for a newer version. Otherwise, I might try Ubuntu instead of rasbian.

**Comment by SloRunner** [comment]
Use NVM, google it, and install latest version ;)

**Comment by GGrandma** [comment]
Thanks, got it working perfectly. Also, holy shit, nvm is so convenient.

**Comment by SloRunner** [comment]
yeah :P i used it on idle bot :P
