### ISSUE TITLE
Error: Disconnected

### ISSUE THREAD

**Issue by SnowAxe** [shanetechwiz/node-steamcardbot#16]
Hello :)

I have a simple question, after searching on Google for about 2 days im completly lost about this error.
I want to know if someone get this error too.
All setting are good.
https://prnt.sc/h96y9k

Thanks in advance ! :+1:

**Comment by SloRunner** [comment]
Wait for shane to reply, heay be a little busy

**Comment by SloRunner** [comment]
Btw is steam account activated (5$ deposit)

**Comment by SnowAxe** [comment]
Yes he don't have any trade restriction :)

**Comment by shanetechwiz** [comment]
@SnowAxe 
I have never gotten this error before.

Try adding

`steamClient.on('error', function(err) { log('An error occured: ' + err); });`

on line 53 and tell me if that works

**Comment by SnowAxe** [comment]
@shanetechwiz Hello and thank's for the reply :)

I have a new error, you can see the screenshot here: http://prntscr.com/hatu56
I already try with another Node Version but, seem got the same error.

Regards,
Snow

**Comment by SnowAxe** [comment]
@shanetechwiz Hello Shane,
It is possible to contact you somewhere ?

I really need your help i don't really like "bump" a thread, as you can see i waited 4 days, but your help is really needed.

Thank's in advance.
