### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by w0zol** [shanetechwiz/node-steamcardbot#17]
_Hello everyone,_

Can someone please edit the `config.js` file and make like a quick tutorial with some examples of what you should write on the different modules?

**Example:** `cards_sold: '', // An example of what sould go here`

Thanks !

**Best Regards,**
w0zol.

**Comment by SloRunner** [comment]
referenced, and patched in pull 18

**Comment by w0zol** [comment]
@SloRunner **Thank you so much !**

**Comment by SloRunner** [comment]
no problem ;) @shanetechwiz can you merge this?
