### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Kladdkaka** [shanetechwiz/node-steamcardbot#5]
Hey!

Nice to see a open source bot on here.

Just wondering how you make sure you send the correct amount of sets to the user, as I see the code, it just sends the x first cards in the inventory, or did I miss anything? :)

Cheers in advance,
Erik

**Comment by SloRunner** [comment]
I will reply asap if the owner won't be faster than me :) i am currently on work but i will explain this question more in depth later

**Comment by Kladdkaka** [comment]
alright! cheers =)

**Comment by SloRunner** [comment]
I think you will have to wait for @shanetechwiz

**Comment by shanetechwiz** [comment]
Hey, sorry about the late reply @Kladdkaka 

What happens is that it checks your inventory for the amount of keys that you actually have and then sends the amount of card sets accordingly.

Check line 162 in bot.js

Hope that helps

**Comment by Kladdkaka** [comment]
Hey!

No problem :) Is the bot running in action anywhere? Would like to take a look. 

Cheers :)

**Comment by shanetechwiz** [comment]
I don't have any running at the moment. I'm not sure if anybody has it up and running

**Comment by SloRunner** [comment]
i should have it soon @shanetechwiz

**Comment by shanetechwiz** [comment]
Ahh, ok nice. Sounds great
