### ISSUE TITLE
Is there a way of modifying the game that the bot is playing so we can place the rate there?

### ISSUE THREAD

**Issue by w0zol** [shanetechwiz/node-steamcardbot#8]
Title

**Comment by skylight-ity** [comment]
yes its ez games.played and you put an array

**Comment by SloRunner** [comment]
just add them after the games played (so you still get the status) i will start working on another one since this dev is not responding anymore

**Comment by w0zol** [comment]
@tuz1k 
@SloRunner 
Where should I do that? config.js? Where?
Also what is "context_id:" ?

**Comment by shanetechwiz** [comment]
Sorry I've been so inactive, I'm a bit too busy for my own good.

@w0zol What exactly are you trying to do? Not sure I get what you mean

**Comment by SloRunner** [comment]
@shane you know when bots play "game" where they display rates, he want that feture if i understand him right... Gonna submit a PR for this feature if you don't mind

**Comment by shanetechwiz** [comment]
@SloRunner Yeah sure, that's fine.

**Comment by w0zol** [comment]
@shanetechwiz No problem.. 
@SloRunner Yes, you got it :)
Will check it out once you publish it..
What are the accepted keys? All of them?
Is there another good source like this where I can learn more?

Also what is the "context_id:"    ( @config.js ? )

**Comment by SloRunner** [comment]
gonna push into PR tomorow when i find out since i normaly use DoctorMcKay npm

**Comment by w0zol** [comment]
@SloRunner I'll be waiting.. Do you know what "context_id:" is?

**Comment by SloRunner** [comment]
Steam inventory... Steam (753 if i am correct has context 6) there is appid and context id for each game inventory...

**Comment by w0zol** [comment]
@SloRunner Thanks !
I'll be waiting for the PR.

**Comment by SloRunner** [comment]
sorry for delay @w0zol, i pushed PR #9 waiting for @shanetechwiz to accept it

**Comment by shanetechwiz** [comment]
@w0zol @SloRunner I've accepted the PR

**Comment by w0zol** [comment]
@SloRunner @shanetechwiz **Thank you both !**

**Comment by SloRunner** [comment]
No problem :)
